# Generated by Django 5.0.1 on 2024-01-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0002_bench_date_bench_reps_bench_sets_alter_bench_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='dead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(null=True)),
                ('sets', models.IntegerField(null=True)),
                ('reps', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='squat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(null=True)),
                ('sets', models.IntegerField(null=True)),
                ('reps', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
