# Generated by Django 5.0.1 on 2024-01-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0005_bench_estim_squat_estim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bench',
            options={'ordering': ('date',)},
        ),
    ]
