# Generated by Django 5.0.1 on 2024-01-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifts', '0006_alter_bench_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dead',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='squat',
            options={'ordering': ('date',)},
        ),
        migrations.RemoveField(
            model_name='bench',
            name='estim',
        ),
        migrations.RemoveField(
            model_name='dead',
            name='estim',
        ),
        migrations.RemoveField(
            model_name='squat',
            name='estim',
        ),
    ]
